### PR TITLE
Add GitPod, Docker-Compose Sample and Update Changelog, Readme

### PR DESCRIPTION
**Pull request by strausmann**
Update symfony/yaml

### CODE REVIEW

**Comment by picrap** [comment]
Hi, sorry to ask, but could you rebase this pull request? There have been a lot of other changes, it’s getting hard to assess.

**Review by picrap — APPROVED** [review]
The only possible problem may be in synology_models.yaml, we’ll perform a post-merge check

**Comment by picrap** [comment]
Don’t bother with my previous comment, I’ll do the merge tonight (french time 😉)

**Comment by picrap** [comment]
Thank you!

**Comment by picrap** [comment]
Gitpod URL in `README.md` does not seem to work…

**Comment by strausmann** [comment]
I will fix this tomorrow. Thanks for your Feedback. 😀

**Comment by picrap** [comment]
I’m sorry you were fastest that my comment edit. It’s fixed.

**Pull request merged**
