### PR TITLE
Fix metadata beta determination

### PR DESCRIPTION
**Pull request by itn3rd77**
The if clause always returned false because the value of ```$this->metadata['beta']``` is ```yes```. I have replaced the ```in_array``` check with the already existing check ```$this->parseBool```.

Now a beta package is correctly show as Beta in the Synology Package Center.

### CODE REVIEW

**Comment by jdel** [comment]
LGTM. @mbirth, does that make sense to you ? According to the synology documentation, beta should be set to `yes` in the `INFO` file. Any other value assumes it's false.

**Comment by jdel** [comment]
Just seen this while going quickly through tests. Why don't we move this logic in the [`isBeta()`](https://github.com/jdel/sspks/blob/a4819825c4e8dac8ad9935bcb9e44a72d65a9203/lib/SSpkS/Package/Package.php#L360) method and use it ?

It is used [in the tests](https://github.com/jdel/sspks/blob/master/tests/PackageTest.php#L76) but nowhere in the code.

The [package filter](https://github.com/jdel/sspks/blob/1041de8ee7334d8e7a81237b8e201be1c11bda88/lib/SSpkS/Package/PackageFilter.php#L123) could also be amended to use `isBeta()` 

@mbirth: what do you think ? Any reason why `isBeta` is not used other than in tests ?

**Comment by itn3rd77** [comment]
I have seen this method but didn't want to dig to deep into the code. Seem reasonable to me to use this method. Is there any reason why ```$this->collectMetadata();```` is not called once in the constructor but in nearly every method inside [Package.php](https://github.com/jdel/sspks/blob/a4819825c4e8dac8ad9935bcb9e44a72d65a9203/lib/SSpkS/Package/Package.php)?

Should I refactor and update my pull request?

**Comment by jdel** [comment]
@itn3rd77 : Most of the code you see here, if not all has been written by @mbirth.

I'd like his input before we start refactoring heavily.

**Pull request merged**
